echo "COMMANDES UTILES :"
echo "- help"
echo "Affiche les commandes et leur mode de fonctionnement"
echo "- curl [url]"
echo "Affiche un site web dans la CLI"
echo "- search [mot]"
echo "Permet de faire une recherche d'un mot dans les noms dossiers/fichiers"
echo "-echo "[texte]" fichier"
echo "Ajouter du texte dans un fichier"
echo "- ps-list"
echo "Affiche les processus en cours (admin)"
echo "- kill-proc [nom du proc]"
echo "kill un processus (admin)"
echo "- login [identifiant]"
echo "Permet de se connecter en tant qu'user spécifique"
echo "- decrypte [clé d'encryption] [texte]"
echo "Permet de decrypter un texte via une clé d'encryption"
echo "- cat [chemin du fichier] alias de **glow** // > installer le package"
echo "Permet d'afficher le contenu d'un fichier"
echo "- fortune"
echo "Répend la bonne fortune (ça peut être utile)"
echo "- cd [chemin]"
echo "Permet de se déplacer vers un dossier, si [chemin] = .. permet de revenir dans le dossier parent"
echo "- ls [chemin]"
echo "Affiche les éléments visible dans le dossier du [chemin]"
echo "- sl [chemin]"
echo "Affiche les éléments visible dans le dossier du [chemin]"
echo "- pwd"
echo "Affiche le chemin absolu du dossier actuel"
echo "- exit"
echo "Permet de se deconnecter de l'utilisateur actuel"
echo "- clear"
echo "Permet de purger la CLI"