#!/bin/bash
SCORE_FILE="/tmp/game_score.txt"
# Liste des dossiers (attention aux slashs à la fin, j'ai mis les deux versions)
dossiers_autorises=("/foret/maison/" "/home/user/" "/home/admin/" "/foret/maison" "/home/user" "/home/admin")

# 1. On vérifie si l'utilisateur a mis un tiret (option -)
if [[ "$1" == -* ]]; then
    echo "La commande ls ne contient aucune option."
    echo "Usage : ls /chemin/du/dossier"
    exit 1
fi

# 2. On vérifie si le dossier est dans la liste
authoriser=false
for path in "${dossiers_autorises[@]}"; do
    if [[ "$1" == "$path" ]]; then
        authoriser=true
        break
    fi
done

# 3. ON UTILISE UNE STRUCTURE SI / SINON (IF / ELSE) UNIQUE
if [ "$authoriser" = true ]; then
    /usr/bin/ls "$1"
    
    # Attribution du score
    if [[ "$1" == *"foret/maison"* ]]; then
        echo 2 > "$SCORE_FILE"
    fi
    # On s'arrête ici car tout s'est bien passé
    exit 0
else
    # Si on arrive ici, c'est QUE le chemin n'était pas dans la liste
    echo "Chemin incorrect"
    exit 1
fi