#!/bin/bash

chemins=("/foret/maison" "/home/user" "/home/admin" "foret/maison" "home/user" "home/admin" "/user" "/admin" "/maison" "/foret" "/home" "user" "admin" "home" "foret" "maison")

if [ $# -gt 2 ]; then
    echo "Erreur : Trop d'arguments"
    exit 1
fi

cible=$1

for chemin in "${chemins[@]}"; do
    if [ "$cible" == "$chemin" ]; then
        /bin/ls "$cible"
        break
    fi
done
